Add filtering to references API
oci-playground/distribution-spec pull request #9
Opened 2022-08-09 18:59 UTC by michaelb990

Signed-off-by: Michael Brown <brownxmi@amazon.com>

2022-08-09 19:02 UTC, sajayantony approved these changes

2022-08-09 19:26 UTC, sudo-bmitch requested changes
Rebase to pickup DCO fixes, we'll also need to add the endpoint API changes, but that's can be a separate commit.

2022-08-09 19:26 UTC, sudo-bmitch commented on spec.md
> +```json
switch to jsonc for syntax highlighting of comments
```suggestion
```jsonc
```

2022-08-09 19:35 UTC, jdolitsky approved these changes

2022-08-09 20:24 UTC, jdolitsky commented
> we'll also need to add the endpoint API changes

@sudo-bmitch - sorry confused.. are you referring to [endpoints table](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints)? separating into a 12a/12b ?

2022-08-09 20:53 UTC, sudo-bmitch commented
> > we'll also need to add the endpoint API changes
> 
> @sudo-bmitch - sorry confused.. are you referring to [endpoints table](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints)? separating into a 12a/12b ?

@jdolitsky Yup. (Much to your likely disappointment.) One line for the API without a filter parameter, and one with.

2022-08-10 02:37 UTC, michaelb990 commented
I think I've made the updates requested. Anything else? @sudo-bmitch @jdolitsky

2022-08-10 03:00 UTC, jdolitsky approved these changes
looks fantastic

2022-08-10 12:26 UTC, sudo-bmitch approved these changes
Looks good, I'm going to pull this one in and then rebase my changes.

2022-08-10 12:27 UTC, merged